#!/bin/bash

# off
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
  echo false
else
  # on
  if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
    echo true
    # connected
  else
    echo false
  fi
fi
