#!/bin/bash

cpu_used=$(top -bn1 | awk '/Cpu/ { print $2}' | sed 's/,/./')

cpu_total=100

case "$1" in
--total) echo "$cpu_total" ;;
--used) echo "$cpu_used" ;;
--percent) echo "$cpu_used" ;;
*) echo "Usage: $0 --total | --used | --percent" ;;
esac
