#!/bin/bash

output=$(ps -eo pid:10,%cpu:10,%mem:10,comm:30 --sort=-%mem | tail -n +2 | head -n 15)

case "$1" in
--1)
  echo "$output" | awk '{print $1}'
  ;;
--2)
  echo "$output" | awk '{print $2}'
  ;;
--3)
  echo "$output" | awk '{print $3}'
  ;;
--4)
  echo "$output" | awk '{print $4 " " $5 " " $6}'
  ;;
*)
  echo "Usage: $0 --1|--2|--3|--4"
  echo "  --1: PID"
  echo "  --2: COMMAND"
  echo "  --3: %CPU"
  echo "  --4: %MEM"
  ;;
esac
